### ISSUE TITLE
wrong IO write text in ECALL test

### ISSUE THREAD

**Issue by jeras** [riscv-non-isa/riscv-arch-test#207]
I assume this is a copy paste typo, it should be `ECALL` and not `EBREAK`.
https://github.com/riscv-non-isa/riscv-arch-test/blob/9141cf9274b610d059199e8aa2e21f54a0bc6a6e/riscv-test-suite/rv64i_m/privilege/src/ecall.S#L34

**Comment by neelgala** [comment]
@jeras thanks for the catch. For now I have pushed a fix for this in https://github.com/riscv-non-isa/riscv-arch-test/pull/205
