### ISSUE TITLE
typo in example target code

### ISSUE THREAD

**Issue by jeras** [riscv-non-isa/riscv-arch-test#208]
Should be `.align` instead of `.alive`.
https://github.com/riscv-non-isa/riscv-arch-test/blob/9141cf9274b610d059199e8aa2e21f54a0bc6a6e/riscv-target/example-target/model_test.h#L27

Somehow I am using this code with the typo but not having any issues.

**Comment by neelgala** [comment]
The description of `.align` is as per the riscv-asm/gnu pseudo ops defined [here](https://github.com/riscv-non-isa/riscv-asm-manual/blob/master/riscv-asm.md#pseudo-ops) 

It is meant to align the end of the signature at a 16byte boundary has demanded in the [Testformat spec](https://github.com/riscv-non-isa/riscv-arch-test/blob/master/spec/TestFormatSpec.adoc#36-the-test-signature)

**Comment by jeras** [comment]
It is not `.align` there is a typo, it is written **alive**, as in all the living creatures, please look at line 27 again.
Since this example is not compiled and executed, there are probably more such typos.

**Comment by neelgala** [comment]
my bad.. should I have read your comment better.. will fix it.
