### ISSUE TITLE
default rvtest_data should be 16-bytes 

### ISSUE THREAD

**Issue by neelgala** [riscv-non-isa/riscv-arch-test#211]
Majority of the tests include a default `rvtest_data` label which contains the single word `0xbabecafe`. This was meant to be used by the load-store tests. However, `ld` tests load the upper bits as 0x0 - which does not break anything but is definitely not the desired behavior of the test. 

Fix would be ensure that the default rvtest_data section has 16 bytes of data (rotated versions of 0xbabecafe). This will also ensure that any other data following it will be starting from at a 16-byte alignment as well

**Comment by neelgala** [comment]
This particular suggestion will require all tests to change. is that acceptable ?

**Comment by allenjbaum** [comment]
An alternative is to make sure the data section ends at a 16 byte alignment
and have the boot code manually store 0xdeadbeef or whatever from that
label until
the previous 16B alignment ( or RVMODEL_DATA_END, whichever comes. That
would be compatible with both old and new, wouldn’t it? The only file that
would be the .h file.
