### ISSUE TITLE
Running Compliance Test for Swerv

### ISSUE THREAD

**Issue by YeuzhiHere** [riscv-non-isa/riscv-arch-test#213]
**Note: I posted this issue in chipalliance/Cores-Swervolf repo as well. Posting here, because its quite active repo. Hope everyone will understand.**

I am trying to do compliance test for swerv core using the mentioned guideline, but my result is;

![0th Pic](https://user-images.githubusercontent.com/58413763/134629083-379e2355-9043-4f95-8275-1f21d153b96e.PNG)

I am new to compliance thing and I will post my each step so that understanding of the whole scenario is clear.

**1.** I am following this section below;
![8th Pic](https://user-images.githubusercontent.com/58413763/134629402-8f2daed7-efff-40cd-b5ca-b65c4fbdf620.PNG)

**2.** When I acted exactly as mentioned in this section, I got these directories (exception is for gnu-riscv-toolchain, which I added myself)
![1st Pic](https://user-images.githubusercontent.com/58413763/134629939-920bd1b7-3043-4a5f-a883-3ed074c76d57.PNG)

**3.** This is my riscv-target directory;
![3rd Pic](https://user-images.githubusercontent.com/58413763/134629876-b3e7d973-4265-4af3-b9ea-a81e6d3e34ad.PNG)

**4.** Upon running this thing as it is, I got few errors like there is no directory named rv32i_m/rv32i in riscv-test-suite. So I changed makefile.include, makefile in riscv-compliance directory and also added rv32i directory in riscv-test-suite. Below are pictures;
![4th Pic](https://user-images.githubusercontent.com/58413763/134630559-7bf316b8-cabf-46f8-839b-bd090dd2f9b7.PNG)
![6th Pic](https://user-images.githubusercontent.com/58413763/134630613-4e126aff-9a89-41c8-a755-d73bb2bb44d6.PNG)
![7th Pic](https://user-images.githubusercontent.com/58413763/134630624-2dc588af-c8cb-430a-a6a5-df4d33dc1130.PNG)
 
**5.** I also edited makefile.include in riscv-target/swerv/device/ directory, which is as under;
![9th Pic](https://user-images.githubusercontent.com/58413763/134631294-aae8014d-732f-4f19-8a06-aba28658da5b.PNG)

**6.** I also got error that model_test.h file not found, so I copied it from some example folder of **riscv-arch-test repo** (might be I did wrong here). Here is pic;
![10th Pic](https://user-images.githubusercontent.com/58413763/134631732-a9357234-ad81-48be-9e02-bee17fbe6f25.PNG)

**7.** Finally here is my work/rv32i_m/rv32i directory;
![11th Pic](https://user-images.githubusercontent.com/58413763/134631993-f71e51b3-0c7b-46d3-9c2c-397701329652.PNG)

**8.** Kindly do guide me and resolve this issue. You can suggest me any other simulator or any repo (where you have done swerv compliance test). If i am missing any detail, plz do mention.

**Comment by YeuzhiHere** [comment]
Another thing, nothing is being written to my **signtaure.output** file

**Comment by neelgala** [comment]
looks like this documentation that you are following is for an older vrsion of the test-framework. Remember you should not be changing anything in the riscv-test-suite directory at all. All changes are required to happen in your riscv-target/swerv/ directory only. You can follow the guide mentioned here : https://github.com/riscv-non-isa/riscv-arch-test/tree/master/doc#porting-a-new-target to port your swerv target for the current framework.

**Comment by YeuzhiHere** [comment]
Thanks @neelgala for your valuable comment. I will follow your recommendations.
