### ISSUE TITLE
Makefile appears to be broken for OPENHW targets

### ISSUE THREAD

**Issue by abukharmeh** [riscv-non-isa/riscv-arch-test#218]
Hi, 
I am trying to compile CV32E40P target and it appears to be broken. 
![image](https://user-images.githubusercontent.com/24764074/137726230-9be860c7-1d14-49a2-aa88-26260c497627.png)

The error reported makes me feel like that project was restructured at some point but that target was not updated !
I tracked when that target was added, and tried with that commit c21a2e86afa3f7d4292a2dd26b759f3f29cde497
and that seems to work fine

Kind regards,
Ibrahim

**Comment by allenjbaum** [comment]
I'm unclear if this is resolved or not;  if everyone understands that it is, could you close this issue. Otherwise coud you clearly state what needs to be done so we can keep track?
