### ISSUE TITLE
F tests

### ISSUE THREAD

**Issue by davidharrishmc** [riscv-non-isa/riscv-arch-test#220]
riscv-arch-test/riscv-test-suite/rv32i_m now has the F directory of tests.

When doing a Make with RISCV_TARGET ? = spike

the riscv-arch-test Makefile looks in riscv-isa-sim/arch_test_target/spike/device/rv32i_m for the RISCV_ISA_ALL.  There is no F directory in arch_test_target, so the F tests don't get made.

I could manually modify arch_test_target to add a F directory, but is there a more graceful solution such that the F tests get made "out of the box"?  Does riscv-isa-sim need an update?

Thank you,

David Harris

**Comment by davidharrishmc** [comment]
Thanks!

**Comment by allenjbaum** [comment]
Is this ready to be closed, or should it wait until thearch_test_target directory in riscv-isa-sim is updated?

**Comment by davidharrishmc** [comment]
Allen,

Not sure if this was a query for me.

I’d love to see riscv-isa-sim arch_test_target updated.

In the meantime, my scripts are manually patching the rv32i_m/F and r64i_m/D makefiles.  Perhaps we will need the same soon for rv64i_m/D and rv32i_m/F.

I don’t know the politics on riscv-isa-sim but am happy to submit pull requests for those Makefiles if it is helpful.

Thanks!

David

**Comment by allenjbaum** [comment]
This will get fixed shortly, and closed, I've been told...

**Comment by allenjbaum** [comment]
Do we want to fix this, or just wait for the cutover to Riscof?

**Comment by davidharrishmc** [comment]
Closing this; will look at riscof.
