### ISSUE TITLE
where to include rtl files

### ISSUE THREAD

**Issue by UditPramod** [riscv-non-isa/riscv-arch-test#229]
For verifying a processor you have done software simulation using imperas and hardware simulation is done and then the log files are compared. Can u pls give me an idea of how to include the RTL files for verifying the processor and how the hardware simulator is done?

**Comment by allenjbaum** [comment]
The README in https://github.com/riscv-non-isa/riscv-arch-test/ doc directory should include the information you need.
Have read it and found something missing?

**Comment by allenjbaum** [comment]
I have not hear a response, so I'm closing this. Reopen if you still have an issue.
