### ISSUE TITLE
Edge signatures are 0xdeadbeef now

### ISSUE THREAD

**Issue by marcfedorow** [riscv-non-isa/riscv-arch-test#240]
Since [this patch](https://github.com/riscv-non-isa/riscv-arch-test/issues/240) in every test that has >= 2048 bytes of signature that edge block fails.
This works if you change last signature block address (2044) to zero (0).
But I think that this should be fixed somehow different.
Reverting "[Automatically adjust base and offset if offset gets too big](https://github.com/riscv-non-isa/riscv-arch-test/commit/49e3e0b2efcbf3cda315d5faf6d3dfb82fc0f505)" works for me.

**Comment by allenjbaum** [comment]
Could you send the name of the failing test and the signature that
mismatched? Obviously that's not supposed to be happening....

**Comment by marcfedorow** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:2.0cm 42.5pt 2.0cm 3.0cm;}
div.WordSection1
	{page:WordSection1;}

**Comment by marcfedorow** [comment]
It is common for all the tests with long enough signature.Just for example let’s tale rv32i andi test.

There is the issue:
```
0848 < 000000020
848 > deadbeef0
848   ^^^^^^^^
```

There is the code:
```
Inst_530:
// rs1_val==6 and imm_val==819,
// opcode: andi ; op1:x10; dest:x11; op1val:0x6;  immval:0x333
TEST_IMM_OP( andi, x11, x10, 0x2, 0x6, 0x333, x2, 2044, x6)
RVTEST_SIGBASE( x2,signature_x2_1)
```

**Comment by allenjbaum** [comment]
I think the problem is that this code will work with the next version of
the framework (which we will cut over to in May)
but not the current one when the explicit offset is 2044 (and I tested the
code with the new framework
I have a fix...

**Comment by Imperas** [comment]
Allen - I don't understand - the tests and the generated signatures are a function of the programs/assembler/macros - and have nothing to do with the script or python that run the RTL or simulators - so can you explain actually what is wrong with this Makefile/Bash framework that will be sorted in a python one - as the programs still are assembled with the same tools, and run on the same RTL or models,  and the signatures are written by the same programs, and the signatures are dumped by the RTL and simulators - so what am I missing... thnx - Simon

**Comment by allenjbaum** [comment]
I don't understand your question. This is something that was intended to be
used in a riscof framework and tested there.
It has absolutely nothing to do with python, it has to do with introducing
it without testing it on the existing tests on the old framework (though I
think it was tested on new tests going into the old framework).
So, left hand, right hand.

**Comment by marcfedorow** [comment]
Can you please revert a patch that introduced this bug before next version of framework is published?

**Comment by allenjbaum** [comment]
Either revert or fix, but yes, we will
