### ISSUE TITLE
riscv-arch-tests on u74

### ISSUE THREAD

**Issue by Ankita-020696** [riscv-non-isa/riscv-arch-test#246]
Hi,
Can riscv-arch-tests ported & executed to FU740?

Thanks

**Comment by indumathiraju** [comment]
Can riscv-arch-tests executed to FU740 without spike?
i got the this error when i execute the riscv-arch-test on u74 board without using spike
oot@Exaleap-Unmatched-Linux-1:~/riscv-arch-test# make
ls: cannot access '/home/root/riscv-arch-test/riscv-target/spike/device/rv32i_m': No such file or directory

============================ VARIABLE INFO ==================================
ROOTDIR: /home/root/riscv-arch-test [origin: file]
WORK: /home/root/riscv-arch-test/work [origin: file]
TARGETDIR: /home/root/riscv-arch-test/riscv-target [origin: file]
RISCV_TARGET: spike [origin: file]
XLEN: 32 [origin: file]
RISCV_DEVICE: I [origin: file]
=============================================================================
