### ISSUE TITLE
No Makefrags

### ISSUE THREAD

**Issue by marcfedorow** [riscv-non-isa/riscv-arch-test#259]
Makefile.include waits for $(act_dir)/Makefrag but there are no Makefrags anymore.

**Comment by pawks** [comment]
The makefile based framework is no longer supported. I guess there are a few files which haven't been removed yet. They are there by mistake and will be removed soon. You should start using [riscof](https://github.com/riscv-software-src/riscof) to run the tests instead.

**Comment by allenjbaum** [comment]
Which files haven't been removed yet? I do notice that 2 target directories are still there.

**Comment by allenjbaum** [comment]
We will remove the target directories, since riscof no longer uses them.
