### ISSUE TITLE
RISC-V COMPLIANCE on SweRV EL2

### ISSUE THREAD

**Issue by KinzaQamar** [riscv-non-isa/riscv-arch-test#261]
Hi,
I have integrated a target for SweRV El2 on branch 1.0. The core is an industry-standard core and it is great if we have a target to run compliance on that. 
If you guys are interested, I can send a PR for that.

**Comment by allenjbaum** [comment]
Could you point at your proposed PR? I'm unclear exactly what you are proposing. Certainly we would like  to ensure that ACTs can be run easily on the SweRV core!

**Comment by allenjbaum** [comment]
I'm not sure what you mean by target. Now that we are using riscof, the new
version of the ACT framework, the target directories have all been removed.
Do you mean you have defined the proper plugins and other support needed by
riscof?

**Comment by allenjbaum** [comment]
No PR has been submitted, so closing this. Reopen if there is something actionable.
