### ISSUE TITLE
Macro used in Crypto Scalar code mislabelled

### ISSUE THREAD

**Issue by allenjbaum** [riscv-non-isa/riscv-arch-test#272]
There was a commit that modified the TEST_RI macro to add a second source register, but didn't change the name.
Effectively, this changed the macro from TEST_RI to TEST_RRI which already existed.
Oddly, TEST_RRI is unused by any test.
The fix is to edit all tests that use TEST_RI to instead use TEST_RRI (since they're currently identical) and delete TEST_RI (since it is redundant)

Nothing else needs to change in the arch-test (including the regenerating the tests), but ctg probably needs to be updated to reflect the actual name

**Comment by allenjbaum** [comment]
We will fix this by deleting the TEST_RI version as part of splitting off the test macros

**Comment by allenjbaum** [comment]
There are no further references to TEST_RI so it should be deleted

**Comment by UmerShahidengr** [comment]
PR #545 has resolved this issue, will close this one after merging #545.
