### ISSUE TITLE
Missing information about the `RVTEST_CASE` argument format in test format spec.

### ISSUE THREAD

**Issue by pawks** [riscv-non-isa/riscv-arch-test#280]
The arguments for the `RVTEST_CASE` are in a specific format and the test format spec needs to be updated to document the format. Something akin to [here](https://github.com/riscv-software-src/riscof/blob/a003752ff95dd5f9153c323dc2eb8ff7a0426dd9/docs/source/testformat.rst#rvtest_case-condition-formatting). Previously it was included in the riscof documentation along with the test format spec. But the test format spec was removed from riscof as it is actively maintained here.

**Comment by allenjbaum** [comment]
I'll add it to the list of things that the new test_format spec will need
to document.

**Comment by allenjbaum** [comment]
Close after updating test format spec (along with issue 190)
