### ISSUE TITLE
Spike and Sail are getting different initial values of misa

### ISSUE THREAD

**Issue by 1danish13** [riscv-non-isa/riscv-arch-test#287]
Hello,
I am writing a basic test of checking read/write access of MISA reg in RISCOF. I am at M-mode, reading the initial values of misa, then updating its value, and re-reading it in the attached test file (.elf also attached). Spike and Sail was getting different initial values in RISCOF. For reference, signature files of spike and sail are also attached for the written test.

CSR MISA value for Spike ==> 0x40141104 (RV32IMC)
CSR MISA value for Sail ==> 0x4014112D (RV32IMACDF)

[issues.zip](https://github.com/riscv-non-isa/riscv-arch-test/files/9646025/issues.zip)

**Comment by allenjbaum** [comment]
Sail will eventually initialize its MISA values based on the ISA string
embedded in the riscv-config YAML, but right now it appears to default to
D&F enabled. I'm not even sure it can be turned off
Spike probably needs to explicitly enable it in a command-line argument. It
would be nice to get them onto the same page, and work is afoot to do this
in Sail, but not spike.
