### ISSUE TITLE
Are Atomic instructions supported?

### ISSUE THREAD

**Issue by algrobman** [riscv-non-isa/riscv-arch-test#315]
Are Atomics (A-Ext) supported? and how to configure riscof to run them?

**Comment by pawks** [comment]
There are no tests for the `A` extension currently. Riscof follows the same method of configuration for all the extensions i.e using the isa yaml.

**Comment by allenjbaum** [comment]
Unknown. I've created an SOW for Dev partners, tiemframe is TBD. Note that it will not be possible to test that they are multi-hart atomic, only they function correctly within a signel hart (even if interrupts occur immediately before or after.

**Comment by algrobman** [comment]
First of all we need tests that check basic functionality of these instructions - like amoadd adds a register value to a memory location - these types of tests shouldn't be hard to generate. (A CPU implementer can mess up even this due the spec misunderstanding). Multiprocessor aspects of these instructions is much more difficult to verify and I'm not sure can be done in this "compliance" tests framework. (Similar as "invisible" aspects of fence/fence.i instruction or interrupts /exceptions handling compliance. )

**Comment by allenjbaum** [comment]
yes - exactly.
The SOW I wrote up does exactly that (and includes some interesting values
as well)
There are lots of tests that need writing, and it's all volunteers that do
it it (some volunteered by the companies emplying them, or by university
grants) so it takes a while.

**Comment by algrobman** [comment]
why can't your test generator  do this? (one, which generated all other RISCV tests)I'm running A-Ext tests from https://github.com/riscv-software-src/riscv-tests, which look very similar to the tests from your repo. ..



    On Monday, February 20, 2023 at 04:22:35 PM CST, Allen Baum ***@***.***> wrote:  
 
 

yes - exactly.
The SOW I wrote up does exactly that (and includes some interesting values
as well)
There are lots of tests that need writing, and it's all volunteers that do
it it (some volunteered by the companies emplying them, or by university
grants) so it takes a while.

**Comment by pawks** [comment]
> why can't your test generator  do this? (one, which generated all other RISCV tests)I'm running A-Ext tests from https://github.com/riscv-software-src/riscv-tests, which look very similar to the tests from your repo.

The test generator needs augmentation to handle the A extension tests. It does not support it in its current state.

**Comment by allenjbaum** [comment]
I think the test have been merged into the repo, so I'm closing this. Reopen if you see something missing

**Comment by algrobman** [comment]
Are there LR/SC tests? I've found AMO*  instructions tests only in A- directory ..

**Comment by allenjbaum** [comment]
This is an issue that has been opened. Supposedly coming shortly.
