### ISSUE TITLE
Useless labels in test cases

### ISSUE THREAD

**Issue by cmuellner** [riscv-non-isa/riscv-arch-test#325]
I found in several test files empty labels like (random example from `fcvt.s.wu_b25-01.S`):

```
signature_x8_0:
    .fill 0*((SIGALIGN)/4),4,0xdeadbeef
````

This does not result in data being allocated (repeat is set to zero).
What's the point of doing that?

Note that this is also in the example in `TestFormatSpec.adoc`.

**Comment by pawks** [comment]
Its an artifact of the test generator. Since it does not generate any data being allocated, its harmless and hence has been ignored thus far.
