### ISSUE TITLE
Unclear label `rvtest_data`

### ISSUE THREAD

**Issue by cmuellner** [riscv-non-isa/riscv-arch-test#326]
Many or all tests use the label `rvtest_data`, which is not documented in the `TestFormatSpec.adoc`.

Note, that the undocumented macros `TEST_LOAD` and `TEST_LOAD_F` use this label.

**Comment by allenjbaum** [comment]
That's an artifact left over from older tests.
New tests will have the test data area begin with the lavel
rvtest_data_begin:, which is generated inside the RVTEST_DATA_BEGIN macro.
Old tests are still compatible with newer versions of the RVTEST_DATA_BEGIN
macro, and we haven't gone back  and removed the labels (which would
involve updating the tests.
So, they are now redundant, harmless labels.

**Comment by pawks** [comment]
The TestFormatSpec is a document which talks about the guidelines for writing the tests. `rvtest_data` is not a required label and is named as such just for verbosity. It is subjective to the test writer and any label can be used to point to the memory location.

**Comment by pawks** [comment]
I do agree on the missing documentation. The macros in `test_macros.h` can definitely use some additional comments to explain them.

**Comment by allenjbaum** [comment]
And... as mentioned elsewhere, I am currently rewriting the test format
spec, splitting into two pieces: what a test developer needs to know, and
what a test user needs to provide to run the tests.

**Comment by UmerShahidengr** [comment]
Another thread to see while updating TestFormatSpec doc (#586 )
