### ISSUE TITLE
Untestable instructions/functionality should be documented

### ISSUE THREAD

**Issue by ssecatch-w** [riscv-non-isa/riscv-arch-test#335]
For example, WFI is not currently testable because there is no mechanism to trigger an external interrupt.
 
Likewise, the atomic extension (A) is not currently available, but if it were, we'd only be able to test the execution updates and not the ability to operate properly concurrently without a mechanism for multiple thread execution. 

This should probably also include the CSR instructions. https://github.com/riscv-non-isa/riscv-arch-test/issues/316 already describes some registers that can demonstrate that the opcodes have proper functionality, but there are many other mandatory registers that will be uncovered due to issues with WARL and/or inability to detect an asynchronous external event.

**Comment by UmerShahidengr** [comment]
This will be taken into account while updating the next version of TestSpecFormat.
CC #586
