### ISSUE TITLE
Test that traps throws compilation error using latest GNU Toolchain

### ISSUE THREAD

**Issue by Abdulwadoodd** [riscv-non-isa/riscv-arch-test#343]
Privilege tests (and c.ebreak) throws error and cannot be compiled using the latest version of the toolchain. I'm using a pre-build nightly release (64-bit-elf-ubuntu) available [here](https://github.com/riscv-collab/riscv-gnu-toolchain/releases/tag/2023.04.29). 
### Reason
Whenever there is a trap, the trap-handler executes `fence.i` instruction [here](https://github.com/riscv-non-isa/riscv-arch-test/blob/main/riscv-test-suite/env/arch_test.h#L903) (which is defined [here](https://github.com/riscv-non-isa/riscv-arch-test/blob/main/riscv-test-suite/env/arch_test.h#L142)). The latest version of the toolchain expects `zifencei` defined as part of ISA string in `march` flag if we want to execute fence.i . And it is not defined in any of the tests under RVTEST_ISA (from where RISCOF picks up ISA string for march), even in Fencei.S test ([link](https://github.com/riscv-non-isa/riscv-arch-test/blob/main/riscv-test-suite/rv32i_m/Zifencei/src/Fencei.S#L13)). Hence, toolchain throws the error on execution of fence instruction without using zifencei in `march` flag.

**Comment by allenjbaum** [comment]
A temporary fix is to define RVMODEL_FENCEI  to be a noop.
This bit of code should only be executed if xTVEC is not writable to point to the trap trampoline, and if it isn't writable, the DUT better have the zifencei extension implemented.

I'm not sure what the the right fix is for this. Implementations are allowed to define it to something else if they have another way to synchonize I&D streams.
