### ISSUE TITLE
FP arithmetic instructions tests

### ISSUE THREAD

**Issue by algrobman** [riscv-non-isa/riscv-arch-test#346]
where are FP arithmetic  instruction tests? I only see FP conversion instructions in D and F directories .(?)

**Comment by allenjbaum** [comment]
Are you looking in just RV64 directories? My understanding is that RV64 uses the tests in the RV32 directory - they're shared.

**Comment by pawks** [comment]
They are automatically set by the macros([link](https://github.com/riscv-non-isa/riscv-arch-test/blob/3caa7840b56aa9db871a35c8daf98e561c7f1084/riscv-test-suite/env/arch_test.h#L194-L206))

**Comment by algrobman** [comment]
any news about atomics?

**Comment by allenjbaum** [comment]
look at the dev-partners spreadsheet here 
https://github.com/orgs/riscv-admin/projects/2/views/19?pane=issue&itemId=23235596
for updates; nothing to do with this issue.
