### ISSUE TITLE
Using new toolchain (12.2) csr opcode errors.

### ISSUE THREAD

**Issue by InspireSemi** [riscv-non-isa/riscv-arch-test#359]
The _zicsr and _zifecei options for -march are no longer assumed if you specify i as an option to -march=

For test cases that have any csr opcodes in them 9DUT or Sail) it will fail the compile with a message:
Error: unrecognized opcode csrr a0,mhartid', extension zicsr' required

Currently the python scripts for generating makefile for both the DUT and Sail use as passed in parameter {0} 
-march={0} which for testing C extension translates to -march=rv64ic  

Changing the python to a fixed value of : -march=rv64imafdc_zicsr_zifencei instead of the {0} fixes this issue and allows the test cases to compile w/o errors. 

I do not know if this is the long term fix for this as some cross-compilers may not support the full extension set, based on how they were built.

**Comment by InspireSemi** [comment]
Example from our DUT that uses csr opcodes in test case:

//RVMODEL_BOOT
#define RVMODEL_BOOT \
.section .text.init; \
.extern _fsignature; \
  csrr a0, mhartid              ;\
  li   a1, 0x00                        ;\
  beq  a1, a0, cont             ;\
55: \
  wfi ;\
  j 55b ;\
cont: ;\
  RVMODEL_IO_INIT;

This allows only 1 hart to proceed to runt he tests and puts any other hart into a wfi state.


Marc Karasek
Principal Software Engineer
M: 678.770.3788

[A close up of a sign    Description automatically generated]
www.inspiresemi.com<http://www.cryptocoretech.com/>

THIS MESSAGE IS INTENDED ONLY FOR THE USE OF THE INDIVIDUAL OR ENTITY TO WHICH IT IS ADDRESSED AND MAY CONTAIN INFORMATION THAT IS PRIVILEGED, CONFIDENTIAL AND/OR EXEMPT FROM DISCLOSURE UNDER APPLICABLE LAW.  If the reader of this message is not the intended recipient or agent responsible for delivering the message to the intended recipient, then you are hereby notified that any dissemination or copying of this communication is strictly prohibited.  If you have received this electronic transmission in error, please delete it from your system without copying it and notify the sender by reply e-mail  so that our address record can be corrected.  Thank you.

**Comment by allenjbaum** [comment]
I think the short description is:
 - you have provided a string (or the riscv-config YAML) that says you
support Zicsr,
 - you require Zicsr in your boot code,
 - but if the test doesn't require Zicsr, it tries to compile the test (and
your boot code) without that string
and therefore the compile fails?

**Comment by MarcKarasek** [comment]
Yes

**Comment by UmerShahidengr** [comment]
I think this issue was resolved, and all existing tests are working on gcc 12.2.
Closing this one, you may reopen it anytime.
