### ISSUE TITLE
More explicit reference to RISCOF would be helpful in the docs

### ISSUE THREAD

**Issue by lev-rumyantsev** [riscv-non-isa/riscv-arch-test#366]
I was trying to find a way to build these tests but couldn't find any instructions. Only after searching the internet I found references that it's build and run using RISCOF. Currently it's mentioned as `For more details on the usage of the current framework see : [RISCOF](https://riscof.readthedocs.io/)`, which sounds like an optional step: if you don't need details you can skip it. But apparently it's the core engine of everything.

So I'd rephase to something along the lines of `Refer to [RISCOF](https://riscof.readthedocs.io/) for instrucitons on how to build these tests`

**Comment by UmerShahidengr** [comment]
Will be taken care of in the next version of documentation updates.
CC #586
