### ISSUE TITLE
No file named model_test.h

### ISSUE THREAD

**Issue by buloruabutata** [riscv-non-isa/riscv-arch-test#375]
I am trying to use this command:riscv64-unknown-linux-gnu-gcc -march=rv32i -mabi=ilp32 -o add-01.elf add-01.S，but model_test.h isn't in this repo, where can I get it?

**Comment by UmerShahidengr** [comment]
model_test.h file comes for DUT or reference plugins.  The plugin environment is set up via config file if you are looking to run these tests using riscof.
In your case, it seems like you are not running your tests using riscof, you can use model_test.h files from here:
If you want to run it on Spike: https://gitlab.com/incoresemi/riscof-plugins/-/tree/master/spike_simple/env
If you are looking to run it on golden model Sail: https://gitlab.com/incoresemi/riscof-plugins/-/tree/master/sail_cSim/env
For your own custom based RISC-V DUT, you have to define your own model_test.h file. You can take reference from above model_test files to define it for your own DUT.
