### ISSUE TITLE
e7d4b281 & bf5ca309 in the ref's signature

### ISSUE THREAD

**Issue by hyperion009** [riscv-non-isa/riscv-arch-test#396]
Hi
it's a first time for me to run a riscv-arch-test. I am using the sail as a reference and find that there are e7d4b281 & bf5ca309 at the begin and end of sail's signature files:
![image](https://github.com/riscv-non-isa/riscv-arch-test/assets/30075118/9d812e78-004c-45dc-9980-975f2fd6f808)
Is this a placeholder or something else?

thanks

**Comment by allenjbaum** [comment]
This are "canary" words which are present to catch errors that go beyond
the bounds of the signature region.
If those words are overwritten, then the framework knows that something
went wrong.
(Assuming that Sail is correct, it would see a signature difference, so it
knows the DUT is acting improperly)

**Comment by allenjbaum** [comment]
I believe this answers your question, so I'm closing this. If this explanation isn't adequate, reopen it
