### ISSUE TITLE
privilege spec 1.11 (2019) is generating mstatush CSR in trap handler which is not defined in that version.

### ISSUE THREAD

**Issue by animesh211** [riscv-non-isa/riscv-arch-test#403]
Hi.
I am using default privilege version in riscof which is using version 1.11 (2019). With the latest version (3.8.0) I am seeing mstatush being present in Trap handler (which is not defined in version 1.11), due to which tests having exceptions are going to mstatush csr in trap handler, then taking illegal exception and not ending.
Can you please check on this once...

**Comment by allenjbaum** [comment]
Ah, yes; that should only be accessed for RV32 && H-exstension implemented.

**Comment by UmerShahidengr** [comment]
We can close this issue, as it has been resolved in PR #406

**Comment by allenjbaum** [comment]
closing, as above
