### ISSUE TITLE
RVMODEL_IO_ASSERT_GPR_RQ used for float point registers

### ISSUE THREAD

**Issue by andreasWallner** [riscv-non-isa/riscv-arch-test#434]
When updating an old testbench where we use a custom `RVMODEL_IO_ASSERT_GPR_EQ` macro in `model_test.h` for reporting I can't build the F & D tests. The reason for this is that `TEST_CASE_F` in `test_macros.h` uses `RVMODEL_IO_ASSERT_GPR_EQ`, passing a float point register as the `destreg`, and our implementation of that macro assumes that `destreg` will be an integer register.

Given that the template also provides two macros that seem to me to be for float comparison (https://github.com/riscv-software-src/riscof/blob/108fa2d4e824b3e37fcff82e4fbbb7243127320b/riscof/Templates/setup/reference/env/model_test.h#L40-L42), should `TEST_CASE_F` call those instead of the GPR version?
If not, did I overlook a way to decide between `mv` and `fmv` depending on the register?

The trail of breadcrumbs:

https://github.com/riscv-non-isa/riscv-arch-test/blob/8a52b016dbe1e2733cc168b9d6e5c93e39059d4d/riscv-test-suite/rv32i_m/F/src/fmin_b1-01.S#L44
passes `f25` as the destreg

https://github.com/riscv-non-isa/riscv-arch-test/blob/8a52b016dbe1e2733cc168b9d6e5c93e39059d4d/riscv-test-suite/env/test_macros.h#L721-L722

passes that on to:

https://github.com/riscv-non-isa/riscv-arch-test/blob/8a52b016dbe1e2733cc168b9d6e5c93e39059d4d/riscv-test-suite/env/test_macros.h#L613-L616

and on to `RVMODEL_IO_ASSERT_GPR_EQ` as `_R`

https://github.com/riscv-software-src/riscof/blob/108fa2d4e824b3e37fcff82e4fbbb7243127320b/riscof/Templates/setup/reference/env/model_test.h#L38

In our specific `RVMODEL_IO_ASSERT_GPR_EQ` we then `mv` that register to `s0` which yields an invalid instruction for this (and many other) case.

```
#define RVMODEL_IO_ASSERT_GPR_EQ(_SP, _R, _I)                                 \
    LOCAL_IO_PUSH(_SP)                                                  \
    mv          s0, _R;     
```

**Comment by allenjbaum** [comment]
I thought PR 426 iswaiting to get approved for that- check that and see if
it fits your needs
