### ISSUE TITLE
Floating point tests are enormous

### ISSUE THREAD

**Issue by Timmmm** [riscv-non-isa/riscv-arch-test#443]
Some of the floating point tests, e.g. `riscv-test-suite/rv32i_m/D/src/fmadd.d_b1-01.S` are enormous, and take a very long time to run in simulation, and a huge amount of memory to compile.

It would be great if they could be split into a larger number of smaller tests.

Is there any documentation for the process of regenerating the tests?

**Comment by allenjbaum** [comment]
This is a duplicate of an existing issue, and we will get around to it when
someone has the resourcxes.
The tests will probably need to take a week just to regenerate, and we need
to augment CTG with a size limit,
 unless someone is clever enough figure out how to split them at the source
level.

**Comment by Timmmm** [comment]
Ah yes I didn't find it when I searched but I did a more extensive search: #307

Is there any documentation for *how* to regenerate them?

**Comment by allenjbaum** [comment]
Regeneration is the same as generation, like any other extension.
But, CTG will need to be updated to split the test generation up once it
has hit certain limits,
and ISAC might need updates to accumulate the coverage from all the split
pieces,
so it isn't going to happen quickly (unless we can get an intern or dev
partner to do it

**Comment by Timmmm** [comment]
Is there any documentation for this generation process? I might do it if it isn't too onerous, but I can't see any documentation for how the existing tests were generated. Do you have any links or scripts? Is it done in CI somewhere?
