### ISSUE TITLE
Zicsr, Zicboz order is wrong in CMO tests

### ISSUE THREAD

**Issue by Timmmm** [riscv-non-isa/riscv-arch-test#472]
See [this comment](https://github.com/riscv-non-isa/riscv-arch-test/commit/e3c5471f58573ea99cd282197251e7c453ba1696#r143001732).

The order of the regex matching the extensions was accidentally changed so that it doesn't match the order that `riscv-config` enforces. That means the CBO tests can never be selected.

I should also note that using regexes here is really bad engineering precisely because things like this are so likely to happen. A better engineered solution would use a *set* to store the set of extensions (clue's in the name) that the ISA string specifies.

**Comment by UmerShahidengr** [comment]
It has been resolved via #473 . Closing this one
