### ISSUE TITLE
Request to split fnmadd.d_b15, fmadd.d_b15, fmsub.d_b15, and fnmsub.d_b15 in rv32i_m

### ISSUE THREAD

**Issue by 2X-ercha** [riscv-non-isa/riscv-arch-test#485]
Is there a plan to split the `fnmadd.d_b15`, `fmadd.d_b15`, `fmsub.d_b15`, and `fnmsub.d_b15` in `rv32i_m` test case to what was done in commit `0d6fa5ca1dceaa916180d7d800781ca67a554931`?

While performing the ACT-Test on our 4-issue out-of-order core, these cases require simulation with terabytes of memory. This seems to place excessive demands on the hardware.

**Comment by UmerShahidengr** [comment]
@2X-ercha Thank you for notifying the issue. The tests have been split in PR #486. It will be merged soon
