### ISSUE TITLE
fnmadd.d_b15, fmadd.d_b15, fnmsub.d_b15, and fmsub.d_b15 have incorrect RVTEST_ISA values

### ISSUE THREAD

**Issue by jordancarlin** [riscv-non-isa/riscv-arch-test#488]
Prior to #486 these tests had `RVTEST_ISA("RV32IFD_Zicsr,RV64IFD_Zicsr")`. 

After the split this was changed to `RVTEST_ISA("RV32IF_Zicsr,RV32IFD_Zicsr,RV64IF_Zicsr,RV64IFD_Zicsr,RV32EF_Zicsr,RV32EFD_Zicsr,RV64EF_Zicsr,RV64EFD_Zicsr")`. 

The new value causes the following error because it is selected with only the F extension even though these are D instructions.
`Error: unrecognized opcode 'fmadd.d f31,f30,f29,f28,dyn', extension 'd' or 'zdinx' required`

**Comment by UmerShahidengr** [comment]
Thanks for the PR @jordancarlin , it will be merged soon and this issue will be closed.

**Comment by jordancarlin** [comment]
Perfect. Thanks for the prompt action.
