### ISSUE TITLE
pyyaml version 

### ISSUE THREAD

**Issue by JAYANTH-IITM** [riscv-non-isa/riscv-arch-test#530]
riscv-config 3.18.3 requires pyyaml==5.2
5.1.1 simply wont support 3.18.3

**Comment by jordancarlin** [comment]
@JAYANTH-IITM I'm curious what the error that prompted this was. With riscv-isac and riscv-ctg requiring >=5.1.1 and riscv-config needing 5.2 there shouldn't be a conflict.

**Comment by JAYANTH-IITM** [comment]
working fine now , thanks
