### ISSUE TITLE
PMP test directory structure differs from all other tests

### ISSUE THREAD

**Issue by jordancarlin** [riscv-non-isa/riscv-arch-test#554]
The PMP test directory structure differs from all other tests. All other tests are inside of a `src` directory inside their respective test folders. The newly added PMP tests skip the `src` folder. This creates unnecessary inconsistency within the tests, especially for systems that explicitly use the path to certain tests (like [CVW](https://github.com/openhwgroup/cvw)).

**Comment by UmerShahidengr** [comment]
Thanks for the quick fix. Going to merge your PR.
