### ISSUE TITLE
fcvt.d.s tests only test non-NaN-boxed input values

### ISSUE THREAD

**Issue by jakubadler** [riscv-non-isa/riscv-arch-test#559]
In [fcvt.d.s_b1-01.S](https://github.com/riscv-non-isa/riscv-arch-test/blob/dev/riscv-test-suite/rv32i_m/D/src/fcvt.d.s_b1-01.S) (and all other fcvt.d.s tests), all the test data use 64 for the `__width__` argument of `NAN_BOXED` even thought the argument is supposed to be float32. I assume it should be 32 in most cases. The way it is now, no NaN-boxing takes place and thus only the one case of the input operand not being correctly NaN-boxed is tested.

**Comment by UmerShahidengr** [comment]
PR #581 has solved this issue, so closing this on. Thank you for raising the issue, and thank you, @Pagerd, for resolving it.
